import type { Metadata } from "next";
import { Geist, Geist_Mono, Island_Moments } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const island = Island_Moments({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-island",
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={island.variable}>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
