import type { Metadata } from "next";

import { Island_Moments, Jost, Poppins, Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";




const island = Island_Moments({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-island",
});
const jost =Jost({
  subsets: ["latin"],
  weight: "100",
  variable: "--font-jost",
});
const poppins =Poppins({
  subsets: ["latin"],
  weight: "100",
  variable: "--font-poppins",
});
const inter =Inter({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-inter",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${island.variable} ${jost.variable} ${poppins.variable} ${inter.variable}`}>
      <body>
     
        {children}
        <Footer />
      </body>
    </html>
  );
}
